import { useState, useRef } from "react";
import { DragDropContext, Droppable, Draggable } from "@hello-pangea/dnd";
import { Trash2, GripVertical, Plus, Settings, Eye, Code2, Copy, Check } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Badge } from "@/components/ui/badge";
import ComponentPreview from "./ComponentPreview";

const ELEMENT_TEMPLATES = [
  { type: "button", label: "Button", defaultProps: { text: "Click me", variant: "primary", size: "md" } },
  { type: "input", label: "Input", defaultProps: { placeholder: "Enter text...", label: "Label" } },
  { type: "card", label: "Card", defaultProps: { title: "Card Title", description: "Card description text here." } },
  { type: "badge", label: "Badge", defaultProps: { text: "Badge", variant: "default" } },
  { type: "text", label: "Text", defaultProps: { content: "Text content", size: "base", weight: "normal" } },
  { type: "divider", label: "Divider", defaultProps: { orientation: "horizontal" } },
  { type: "avatar", label: "Avatar", defaultProps: { initials: "AB", size: "md" } },
  { type: "alert", label: "Alert", defaultProps: { message: "This is an alert", variant: "info" } },
];

function PropEditor({ element, onChange }) {
  const props = element.props;
  return (
    <div className="space-y-3 p-3">
      <div className="text-xs font-semibold text-slate-400 uppercase tracking-wider">Properties</div>
      {Object.entries(props).map(([key, value]) => (
        <div key={key} className="space-y-1">
          <Label className="text-xs text-slate-400">{key}</Label>
          <Input
            value={value}
            onChange={e => onChange(element.id, { ...props, [key]: e.target.value })}
            className="h-7 text-xs bg-white/5 border-white/10 text-white"
          />
        </div>
      ))}
    </div>
  );
}

export default function ComponentCanvas({ componentName }) {
  const [elements, setElements] = useState([]);
  const [selectedId, setSelectedId] = useState(null);
  const [view, setView] = useState("preview"); // preview | code
  const [copied, setCopied] = useState(false);

  const addElement = (template) => {
    const el = { id: `${template.type}-${Date.now()}`, type: template.type, props: { ...template.defaultProps } };
    setElements(prev => [...prev, el]);
    setSelectedId(el.id);
  };

  const removeElement = (id) => {
    setElements(prev => prev.filter(e => e.id !== id));
    if (selectedId === id) setSelectedId(null);
  };

  const updateProps = (id, newProps) => {
    setElements(prev => prev.map(e => e.id === id ? { ...e, props: newProps } : e));
  };

  const onDragEnd = (result) => {
    if (!result.destination) return;
    const items = Array.from(elements);
    const [moved] = items.splice(result.source.index, 1);
    items.splice(result.destination.index, 0, moved);
    setElements(items);
  };

  const generateCode = () => {
    const lines = [`// ${componentName || "Component"} - Generated by Design System Visualizer`, ""];
    elements.forEach(el => {
      if (el.type === "button") lines.push(`<button className="btn btn-${el.props.variant}">${el.props.text}</button>`);
      else if (el.type === "input") lines.push(`<input placeholder="${el.props.placeholder}" />`);
      else if (el.type === "card") lines.push(`<div className="card">\n  <h3>${el.props.title}</h3>\n  <p>${el.props.description}</p>\n</div>`);
      else if (el.type === "badge") lines.push(`<span className="badge badge-${el.props.variant}">${el.props.text}</span>`);
      else if (el.type === "text") lines.push(`<p className="text-${el.props.size} font-${el.props.weight}">${el.props.content}</p>`);
      else if (el.type === "divider") lines.push(`<hr />`);
      else if (el.type === "avatar") lines.push(`<div className="avatar">${el.props.initials}</div>`);
      else if (el.type === "alert") lines.push(`<div className="alert alert-${el.props.variant}">${el.props.message}</div>`);
    });
    return lines.join("\n");
  };

  const copyCode = () => {
    navigator.clipboard.writeText(generateCode());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const selected = elements.find(e => e.id === selectedId);

  return (
    <div className="h-full flex flex-col">
      {/* Toolbar */}
      <div className="flex items-center gap-2 p-3 border-b border-white/10 bg-slate-900/50">
        <div className="flex gap-1">
          {ELEMENT_TEMPLATES.map(t => (
            <button
              key={t.type}
              onClick={() => addElement(t)}
              className="flex items-center gap-1 px-2 py-1 text-xs rounded bg-white/5 hover:bg-white/10 text-slate-300 border border-white/10 transition-colors"
            >
              <Plus className="w-3 h-3" /> {t.label}
            </button>
          ))}
        </div>
        <div className="ml-auto flex items-center gap-2">
          <div className="flex rounded-lg overflow-hidden border border-white/10">
            <button onClick={() => setView("preview")} className={`px-3 py-1 text-xs flex items-center gap-1 transition-colors ${view === "preview" ? "bg-white/15 text-white" : "bg-transparent text-slate-400 hover:text-white"}`}>
              <Eye className="w-3 h-3" /> Preview
            </button>
            <button onClick={() => setView("code")} className={`px-3 py-1 text-xs flex items-center gap-1 transition-colors ${view === "code" ? "bg-white/15 text-white" : "bg-transparent text-slate-400 hover:text-white"}`}>
              <Code2 className="w-3 h-3" /> Code
            </button>
          </div>
          {view === "code" && (
            <button onClick={copyCode} className="px-2 py-1 text-xs flex items-center gap-1 text-slate-400 hover:text-white transition-colors">
              {copied ? <Check className="w-3 h-3 text-green-400" /> : <Copy className="w-3 h-3" />}
              {copied ? "Copied" : "Copy"}
            </button>
          )}
        </div>
      </div>

      <div className="flex-1 flex overflow-hidden">
        {/* Canvas Area */}
        <div className="flex-1 overflow-y-auto">
          {view === "preview" ? (
            <div className="p-6 min-h-full">
              {elements.length === 0 ? (
                <div className="h-64 flex flex-col items-center justify-center border-2 border-dashed border-white/10 rounded-xl text-slate-500">
                  <Plus className="w-8 h-8 mb-2 opacity-40" />
                  <p className="text-sm">Add elements using the toolbar above</p>
                  <p className="text-xs mt-1 opacity-60">Drag to reorder</p>
                </div>
              ) : (
                <DragDropContext onDragEnd={onDragEnd}>
                  <Droppable droppableId="canvas">
                    {(provided) => (
                      <div {...provided.droppableProps} ref={provided.innerRef} className="space-y-3">
                        {elements.map((el, index) => (
                          <Draggable key={el.id} draggableId={el.id} index={index}>
                            {(provided, snapshot) => (
                              <div
                                ref={provided.innerRef}
                                {...provided.draggableProps}
                                onClick={() => setSelectedId(el.id)}
                                className={`group relative rounded-xl border transition-all cursor-pointer ${selectedId === el.id ? "border-blue-500/50 bg-blue-500/5" : "border-white/10 hover:border-white/20"} ${snapshot.isDragging ? "shadow-2xl shadow-black/50 opacity-90" : ""}`}
                              >
                                <div className="absolute top-2 left-2 opacity-0 group-hover:opacity-100 transition-opacity z-10" {...provided.dragHandleProps}>
                                  <GripVertical className="w-4 h-4 text-slate-500" />
                                </div>
                                <div className="absolute top-2 right-2 flex gap-1 opacity-0 group-hover:opacity-100 transition-opacity z-10">
                                  <button onClick={(e) => { e.stopPropagation(); setSelectedId(el.id); }} className="p-1 rounded bg-slate-700 hover:bg-slate-600">
                                    <Settings className="w-3 h-3 text-slate-300" />
                                  </button>
                                  <button onClick={(e) => { e.stopPropagation(); removeElement(el.id); }} className="p-1 rounded bg-red-900/50 hover:bg-red-800">
                                    <Trash2 className="w-3 h-3 text-red-300" />
                                  </button>
                                </div>
                                <div className="p-4 pl-8">
                                  <ComponentPreview element={el} />
                                </div>
                              </div>
                            )}
                          </Draggable>
                        ))}
                        {provided.placeholder}
                      </div>
                    )}
                  </Droppable>
                </DragDropContext>
              )}
            </div>
          ) : (
            <div className="p-4">
              <pre className="text-xs text-green-300 font-mono bg-slate-950 rounded-xl p-4 border border-white/10 overflow-x-auto whitespace-pre-wrap">
                {generateCode() || "// Add elements to generate code"}
              </pre>
            </div>
          )}
        </div>

        {/* Props Panel */}
        {selected && (
          <div className="w-56 border-l border-white/10 bg-slate-900/50 overflow-y-auto">
            <div className="flex items-center justify-between p-3 border-b border-white/10">
              <span className="text-xs font-medium text-white capitalize">{selected.type}</span>
              <Badge variant="outline" className="text-xs border-white/20 text-slate-400">{selected.id.split("-")[0]}</Badge>
            </div>
            <PropEditor element={selected} onChange={updateProps} />
          </div>
        )}
      </div>
    </div>
  );
}